


- task: Kubernetes@1
  displayName: Deploy ServiceMonitor
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    namespace: default
    command: apply
    useConfigurationFile: true
    configuration: $(Pipeline.Workspace)/manifests/servicemonitor.yaml