apiVersion: v1
kind: Service
metadata:
    name: multicloudapp
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      name: http
      targetPort: 8080
    selector:
        app: multicloudapp
